import type { Metadata } from "next";
import { Josefin_Sans, Jost, Kumbh_Sans, Open_Sans, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const kumb = Kumbh_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kumb.className}>
       <Navbar/>
        {children}</body>
    </html>
  );
}
